import type { MedicalClinicalCase } from "./medicineData";

export const additionalMedicalClinicalCases: MedicalClinicalCase[] = [
  {
    id: "acute-coronary-syndrome",
    area: "Cardiologia e emergência",
    setting: "Pronto atendimento",
    difficulty: "Ciclo clínico",
    durationMinutes: 18,
    title: "Pressão torácica em evolução",
    subtitle: "Conecte sintomas, tempo, ECG e troponina sem depender de um único dado para fechar o raciocínio.",
    patient: "Homem de 54 anos · cenário inteiramente fictício",
    focus: "Reconhecer uma possível síndrome coronariana aguda, organizar avaliação tempo-dependente e preservar diagnósticos concorrentes.",
    sensitive: false,
    triage: [
      { label: "PA", value: "152/94 mmHg", tone: "attention" },
      { label: "FC", value: "106 bpm", tone: "attention" },
      { label: "FR", value: "23 irpm", tone: "attention" },
      { label: "SpO₂", value: "95% AA", tone: "attention" },
    ],
    steps: [
      {
        id: "acs-recognition",
        label: "Reconhecimento",
        title: "Trate o tempo como dado clínico",
        release: ["Pressão retroesternal forte há 35 minutos", "Irradiação para o braço esquerdo", "Sudorese, náusea e falta de ar", "Hipertensão e colesterol elevado; episódio mais leve ao subir uma ladeira"],
        question: "Qual é a leitura inicial mais segura?",
        options: ["Ansiedade confirmada pela situação de trabalho", "Possível síndrome coronariana aguda que exige avaliação imediata", "Dor musculoesquelética confirmada pela idade", "Problema digestivo sem necessidade de ECG"],
        answer: 1,
        explanation: "Pressão torácica persistente com irradiação e sintomas associados é compatível com uma emergência cardiovascular possível. A prioridade é avaliação imediata e estruturada, não um diagnóstico definitivo pela história isolada.",
        reflectionPrompt: "Resuma em uma frase o padrão temporal, os sintomas associados e por que a avaliação não deve ser adiada.",
        placeholder: "Pessoa de 54 anos com… há…, associada a…, exigindo…",
        sourceId: "ahaChestPain2021",
        hint: "O exercício avalia reconhecimento de risco antes da confirmação etiológica.",
      },
      {
        id: "acs-ecg",
        label: "ECG inicial",
        title: "Um traçado inicial informa, mas nem sempre encerra",
        release: ["ECG obtido durante os sintomas", "Ritmo sinusal a 105 bpm", "Depressão discreta e dinâmica do segmento ST em derivações laterais", "Não há elevação persistente do segmento ST neste registro"],
        question: "Qual interpretação mantém melhor a segurança do raciocínio?",
        options: ["Síndrome coronariana excluída porque não há elevação persistente de ST", "Alterações isquêmicas possíveis precisam ser integradas aos sintomas e a avaliações seriadas", "Infarto confirmado apenas pela frequência cardíaca", "ECG é irrelevante quando existe náusea"],
        answer: 1,
        explanation: "A ausência de elevação persistente de ST não exclui síndrome coronariana aguda. Sintomas, mudanças eletrocardiográficas, biomarcadores e evolução temporal precisam ser interpretados em conjunto.",
        reflectionPrompt: "Explique o que o ECG apoia, o que ele não confirma sozinho e qual informação temporal ainda importa.",
        placeholder: "O ECG mostra…; sozinho não…; ainda preciso acompanhar…",
        sourceId: "ahaAcs2025",
      },
      {
        id: "acs-troponin",
        label: "Biomarcador seriado",
        title: "Procure mudança, não apenas um número",
        release: ["Troponina cardíaca de alta sensibilidade inicial próxima ao limite do ensaio", "Nova amostra mostra elevação acima do percentil de referência e variação ascendente", "Os limites dependem do método e do laboratório", "A dor diminui, mas não desaparece completamente"],
        question: "O que a variação seriada acrescenta?",
        options: ["Demonstra sozinha a artéria responsável", "Apoia lesão miocárdica aguda e precisa ser integrada ao contexto para classificar a causa", "Exclui todos os diagnósticos não cardíacos", "Torna sintomas e ECG desnecessários"],
        answer: 1,
        explanation: "Troponina de alta sensibilidade é central para detectar lesão miocárdica, e a mudança seriada ajuda a reconhecer um processo agudo. Ainda é necessário integrar apresentação clínica, ECG e possíveis causas alternativas.",
        reflectionPrompt: "Diferencie em duas frases lesão miocárdica detectada e a definição da causa dessa lesão.",
        placeholder: "A troponina indica…; para atribuir a causa, é preciso…",
        sourceId: "ahaHeartAttackDiagnosis",
      },
      {
        id: "acs-imaging",
        label: "Imagem dirigida",
        title: "Use a imagem para responder uma pergunta clínica",
        release: ["Ecocardiograma à beira do leito mostra alteração segmentar discreta da contratilidade", "Não há derrame pericárdico volumoso", "A raiz da aorta não está dilatada nesta janela", "O exame não identifica sozinho o mecanismo nem substitui ECG e biomarcadores"],
        question: "Qual é o papel mais adequado desse achado?",
        options: ["Confirmar sozinho a etiologia e encerrar o caso", "Acrescentar evidência funcional ao conjunto, preservando os limites do método", "Excluir toda síndrome aórtica possível", "Definir tratamento individual sem avaliação da equipe"],
        answer: 1,
        explanation: "A imagem cardíaca pode acrescentar evidência de alteração funcional e identificar complicações ou diagnósticos alternativos. Ela deve responder a uma pergunta e ser integrada aos outros dados, não usada como confirmação isolada fora do contexto.",
        reflectionPrompt: "Diga qual pergunta o ecocardiograma ajuda a responder e quais conclusões ele não permite sozinho neste cenário.",
        placeholder: "Ajuda a avaliar…; não permite concluir sozinho…",
        sourceId: "ahaHeartAttackDiagnosis",
      },
      {
        id: "acs-differential",
        label: "Diferenciais perigosos",
        title: "Não deixe uma hipótese forte apagar ameaças concorrentes",
        release: ["Pulsos são simétricos e não há déficit neurológico focal", "Não há hemoptise ou sinal clínico unilateral de trombose", "Dor não é reprodutível à palpação", "A equipe mantém vigilância para síndrome aórtica e embolia pulmonar conforme evolução"],
        question: "Qual formulação é mais apropriada nesta etapa?",
        options: ["Síndrome coronariana provável; diferenciais tempo-dependentes continuam sendo verificados", "Embolia pulmonar definitivamente excluída pelos pulsos", "Síndrome aórtica impossível sem hipertensão extrema", "Dor cardíaca confirmada porque não dói à palpação"],
        answer: 0,
        explanation: "Uma hipótese cardiovascular forte não elimina automaticamente outras causas graves de dor torácica. A equipe usa história, exame, probabilidade e exames dirigidos para reduzir incerteza sem criar atrasos perigosos.",
        reflectionPrompt: "Compare a hipótese principal com dois diagnósticos concorrentes e cite quais dados ainda mudariam a prioridade.",
        placeholder: "Principal: … | Concorrente 1: … | Concorrente 2: … | Mudaria com…",
        sourceId: "ahaChestPain2021",
      },
      {
        id: "acs-synthesis",
        label: "Síntese",
        title: "Feche o caso sem transformar simulação em prescrição",
        release: ["Sintomas permanecem compatíveis com isquemia miocárdica", "ECG apresenta alteração dinâmica sem elevação persistente de ST", "Troponina seriada mostra padrão ascendente", "Avaliação e decisões seguem protocolo institucional e equipe especializada"],
        question: "Qual síntese é mais precisa?",
        options: ["Ansiedade, porque o episódio ocorreu no trabalho", "Síndrome coronariana aguda sem elevação persistente de ST é a hipótese operacional, apoiada pelo conjunto e ainda dependente de avaliação clínica completa", "Artéria coronária específica identificada sem imagem", "Alta segura porque a dor diminuiu"],
        answer: 1,
        explanation: "A síntese correta reúne sintomas, ECG e biomarcador, declara o grau de sustentação e preserva os limites do cenário. A simulação não define tratamento individual nem substitui protocolos e avaliação profissional.",
        reflectionPrompt: "Escreva três frases: hipótese operacional, evidências que a sustentam e limites ainda presentes.",
        placeholder: "Hipótese: … | Evidências: … | Limites: …",
        sourceId: "ahaAcs2025",
      },
    ],
    completion: {
      title: "Coração conectado: da estrutura ao caso",
      summary: "Você integrou reconhecimento de risco, ECG, troponina seriada, diferenciais e síntese clínica sem depender de um único achado.",
      takeaways: ["Dor torácica aguda pode ser tempo-dependente", "ECG e troponina são interpretados em conjunto e ao longo do tempo", "Lesão miocárdica não nomeia sozinha a causa", "Uma hipótese forte não apaga diferenciais perigosos"],
    },
  },
  {
    id: "open-tibia-trauma",
    area: "Trauma e ortopedia",
    setting: "Sala de emergência",
    difficulty: "Internato",
    durationMinutes: 24,
    title: "Fratura exposta após colisão",
    subtitle: "Atendimento progressivo de um trauma de alta energia com hemorragia, lesão de partes moles e risco neurovascular.",
    patient: "Homem de 31 anos · cenário inteiramente fictício",
    focus: "Priorizar ameaças à vida, documentar o membro e organizar o cuidado ortoplástico sem perder tempo crítico.",
    sensitive: true,
    sensitivityNote: "Fratura exposta, sangue e tecido profundo visível.",
    visual: {
      image: "/medicine/clinical/open-tibia-fracture-v1.png",
      alt: "Ilustração sintética de uma fratura exposta da tíbia em ambiente de emergência",
      caption: "Imagem sintética para treino de observação. Não representa paciente real e não deve ser usada para diagnóstico.",
    },
    triage: [
      { label: "PA", value: "92/58 mmHg", tone: "critical" },
      { label: "FC", value: "126 bpm", tone: "critical" },
      { label: "FR", value: "26 irpm", tone: "attention" },
      { label: "SpO₂", value: "95% AA", tone: "attention" },
    ],
    steps: [
      {
        id: "trauma-primary-survey",
        label: "Avaliação primária",
        title: "O membro chama atenção, mas o paciente vem primeiro",
        release: ["Colisão entre motocicleta e automóvel há 25 minutos", "Está alerta, responde adequadamente e mantém via aérea pérvia", "Sangramento importante na perna direita, ainda sem controle completo", "Pele fria, enchimento capilar global lentificado e pulso radial fino"],
        data: [{ label: "PA", value: "92/58", tone: "critical" }, { label: "FC", value: "126", tone: "critical" }, { label: "Glasgow", value: "15", tone: "normal" }, { label: "Dor", value: "9/10", tone: "critical" }],
        question: "Qual ação organiza melhor os primeiros minutos desta simulação?",
        options: ["Começar pela classificação definitiva da fratura", "Executar avaliação estruturada, controlar a hemorragia externa e reavaliar a perfusão", "Levar diretamente para radiografia antes de intervir", "Irrigar profundamente a ferida na sala de trauma"],
        answer: 1,
        explanation: "Em trauma maior, ameaças imediatas à vida e hemorragia significativa precisam ser reconhecidas e tratadas em uma sequência estruturada. A aparência do membro não deve desviar a equipe da avaliação global, mas o sangramento externo precisa de controle rápido e reavaliação frequente.",
        reflectionPrompt: "Registre sua avaliação primária em ordem de prioridade e explique como a hipotensão e a taquicardia mudam a urgência do cenário.",
        placeholder: "A/B: … | C: … | D/E: … | O choque é possível porque…",
        sourceId: "niceMajorTrauma",
        hint: "Comece pelas ameaças que podem matar antes da definição anatômica completa da fratura.",
      },
      {
        id: "trauma-wound-exam",
        label: "Exposição e exame",
        title: "Leia a ferida sem causar dano adicional",
        release: ["Ferida anteromedial extensa no terço médio da perna", "Fragmentos ósseos e tecido profundo são visíveis", "Há terra e pequenos detritos superficiais", "Pé inicialmente pálido, mas com pulso pedioso palpável após alinhamento cuidadoso"],
        question: "Qual documentação é indispensável antes e depois de qualquer realinhamento ou imobilização?",
        options: ["Somente uma nota sobre o tamanho da ferida", "Apenas a intensidade da dor", "Estado neurovascular comparativo, horário da avaliação, nervos testados e pulsos examinados", "Somente uma fotografia sem registro escrito"],
        answer: 2,
        explanation: "O estado neurovascular deve ser examinado e registrado de forma comparativa e seriada, incluindo sensibilidade, função motora e pulsos. A fotografia pode apoiar a comunicação clínica dentro de regras de governança, mas não substitui uma documentação estruturada e temporal.",
        reflectionPrompt: "Descreva exatamente quais funções motoras, sensitivas e circulatórias você registraria nos dois membros e quando repetiria o exame.",
        placeholder: "Motor: … | Sensitivo: … | Pulsos/perfusão: … | Reavaliar após…",
        sourceId: "niceComplexFracture",
        hint: "Pense no que pode mudar após alinhamento, curativo, imobilização ou deterioração.",
      },
      {
        id: "trauma-initial-protection",
        label: "Proteção inicial",
        title: "Proteja a ferida e não atrase o destino correto",
        release: ["Hemorragia controlada após medidas iniciais", "A equipe confirma fratura exposta de osso longo", "Ainda não foi administrada profilaxia antimicrobiana no pré-hospitalar", "O centro atual dispõe de equipe ortopédica e plástica de trauma"],
        question: "Qual conjunto é mais coerente com o cuidado inicial recomendado no hospital?",
        options: ["Irrigação vigorosa na sala, fechamento imediato e alta", "Curativo salino oclusivo, antibiótico intravenoso imediato conforme protocolo e cuidado ortoplástico", "Aguardar cultura superficial antes de qualquer medida", "Remover repetidamente o curativo para acompanhar a aparência"],
        answer: 1,
        explanation: "A diretriz recomenda não irrigar fraturas expostas de ossos longos no departamento de emergência antes da excisão da ferida. Um curativo adequado, profilaxia antimicrobiana sem atraso e encaminhamento para cuidado ortoplástico reduzem demora e manipulação desnecessária.",
        reflectionPrompt: "Explique por que manipulação repetida, irrigação improvisada e espera por exames não devem atrasar as medidas iniciais deste cenário.",
        placeholder: "Evito … porque… | Priorizo … porque…",
        sourceId: "niceComplexFracture",
      },
      {
        id: "trauma-imaging",
        label: "Imagem e extensão",
        title: "Defina a lesão depois da estabilização inicial",
        release: ["Radiografias mostram fratura cominutiva da diáfise tibial e fratura associada da fíbula", "Não há corpo estranho radiopaco evidente", "Hemoglobina inicial 10,7 g/dL e lactato 3,8 mmol/L", "A dor aumenta com extensão passiva dos dedos durante a observação"],
        data: [{ label: "Hb", value: "10,7 g/dL", tone: "attention" }, { label: "Lactato", value: "3,8 mmol/L", tone: "critical" }, { label: "Pulso pedioso", value: "Presente", tone: "normal" }, { label: "Dor passiva", value: "Progressiva", tone: "critical" }],
        question: "Qual nova preocupação não pode ser descartada apenas porque o pulso pedioso está presente?",
        options: ["Síndrome compartimental em evolução", "Anemia ferropriva crônica confirmada", "Meningite bacteriana", "Lesão isolada da pele sem risco profundo"],
        answer: 0,
        explanation: "Dor progressiva e dor à extensão passiva exigem vigilância para síndrome compartimental. A presença de pulso não exclui aumento perigoso da pressão compartimental, e a avaliação clínica seriada deve ser registrada durante as primeiras horas do cuidado.",
        reflectionPrompt: "Integre mecanismo, achados de imagem, perfusão e dor em uma lista de problemas priorizada, incluindo o que precisa de reavaliação seriada.",
        placeholder: "1) … ameaça imediata | 2) … risco do membro | 3) … monitorar…",
        sourceId: "niceComplexFracture",
      },
      {
        id: "trauma-orthoplastic-plan",
        label: "Plano ortoplástico",
        title: "A ferida e o osso são um único problema",
        release: ["A lesão é classificada como trauma aberto de alta energia", "A ferida está contaminada, sem sangramento arterial incontrolável", "A pessoa permanece hemodinamicamente responsiva às medidas de ressuscitação", "Ortopedia e cirurgia plástica avaliam conjuntamente o membro"],
        question: "Qual princípio orienta melhor o planejamento definitivo?",
        options: ["Decidir amputação apenas por um escore numérico", "Separar completamente o tratamento ósseo do tecido mole", "Realizar avaliação multidisciplinar e coordenar excisão, estabilização e cobertura de partes moles", "Fechar a pele antes de avaliar tecido desvitalizado"],
        answer: 2,
        explanation: "Fraturas expostas graves exigem abordagem ortoplástica coordenada. Decisões sobre salvamento do membro não devem depender isoladamente de um escore; excisão da ferida, estabilização e cobertura precisam ser planejadas em conjunto com atenção à viabilidade e à segurança global.",
        reflectionPrompt: "Descreva como você apresentaria o caso à equipe ortoplástica, incluindo estabilidade, contaminação, neurovascular, imagem e riscos imediatos.",
        placeholder: "Paciente… | Ferida… | Neurovascular… | Imagem… | Riscos…",
        sourceId: "niceComplexFracture",
      },
      {
        id: "trauma-synthesis",
        label: "Síntese e transferência",
        title: "Faça uma passagem de caso que preserve o tempo crítico",
        release: ["Hemorragia externa está controlada e sinais vitais melhoraram", "Antibiótico e curativo foram administrados conforme protocolo local", "Exame neurovascular seriado está documentado", "A pessoa seguirá para manejo ortoplástico definitivo com vigilância compartimental"],
        question: "Qual síntese é mais segura para encerrar o exercício?",
        options: ["Fratura simples, sem risco porque há pulso", "Trauma aberto de alta energia estabilizado inicialmente, ainda com risco infeccioso, vascular e compartimental que exige cuidado especializado", "Ferida cutânea já resolvida pelo curativo", "Caso concluído sem necessidade de documentação adicional"],
        answer: 1,
        explanation: "A síntese precisa declarar o mecanismo, as ameaças tratadas, o estado neurovascular, as medidas realizadas e os riscos ainda ativos. Controle inicial não equivale a resolução, e o membro continua exigindo cuidado especializado, documentação e reavaliação.",
        reflectionPrompt: "Escreva uma passagem estruturada com situação, contexto, avaliação e recomendação, sem omitir os riscos que permanecem após a estabilização.",
        placeholder: "Situação: … | Contexto: … | Avaliação: … | Recomendação: …",
        sourceId: "niceComplexFracture",
      },
    ],
    completion: {
      title: "Trauma concluído: vida, membro e tempo alinhados",
      summary: "Você priorizou estabilidade, controlou a hemorragia, documentou o estado neurovascular e estruturou o cuidado ortoplástico sem transformar a imagem em toda a história.",
      takeaways: ["A avaliação global precede a classificação da fratura", "Pulso presente não elimina todos os riscos do membro", "Ferida e osso exigem planejamento conjunto", "Documentação seriada faz parte do cuidado"],
    },
  },
  {
    id: "infected-diabetic-foot",
    area: "Endocrinologia e infectologia",
    setting: "Pronto atendimento",
    difficulty: "Ciclo clínico",
    durationMinutes: 22,
    title: "Úlcera neuropática com sinais sistêmicos",
    subtitle: "Avalie gravidade, perfusão, profundidade e possibilidade de infecção óssea em um pé diabético ativo.",
    patient: "Mulher de 58 anos · cenário inteiramente fictício",
    focus: "Reconhecer ameaça ao membro e à vida, classificar a infecção e organizar investigação multidisciplinar.",
    sensitive: true,
    sensitivityNote: "Ferida profunda, secreção e tecido inflamado.",
    visual: {
      image: "/medicine/clinical/infected-diabetic-foot-v1.png",
      alt: "Ilustração sintética de uma úlcera plantar infectada em pé diabético",
      caption: "Imagem sintética para treino de observação. A aparência isolada não define profundidade, perfusão ou diagnóstico.",
    },
    triage: [{ label: "Temperatura", value: "38,6 °C", tone: "critical" }, { label: "FC", value: "116 bpm", tone: "critical" }, { label: "PA", value: "98/62 mmHg", tone: "attention" }, { label: "Glicemia", value: "286 mg/dL", tone: "critical" }],
    steps: [
      {
        id: "foot-red-flags",
        label: "Risco imediato",
        title: "Não reduza o caso a uma ferida local",
        release: ["Diabetes tipo 2 há 17 anos, com seguimento irregular", "Ferida plantar percebida há três semanas", "Febre e prostração iniciadas nas últimas 24 horas", "Familiar relata piora rápida do inchaço e do odor"],
        question: "Qual classificação inicial muda imediatamente a prioridade deste atendimento?",
        options: ["Problema cosmético sem urgência", "Pé diabético ativo com sinais sistêmicos e possível ameaça ao membro ou à vida", "Neuropatia estável sem ferida", "Calosidade isolada de baixo risco"],
        answer: 1,
        explanation: "Úlcera acompanhada de febre ou sinais sistêmicos exige avaliação aguda e envolvimento do serviço multidisciplinar. A combinação não deve ser tratada apenas como lesão local, porque infecção profunda, isquemia e sepse precisam ser procuradas rapidamente.",
        reflectionPrompt: "Produza uma representação do problema que inclua duração, diabetes, progressão local, sinais sistêmicos e o risco que você deseja excluir primeiro.",
        placeholder: "Pessoa com… apresenta… há…, agora com…, preocupando por…",
        sourceId: "niceDiabeticFoot",
        hint: "Febre e instabilidade transformam uma lesão local em um problema sistêmico potencial.",
      },
      {
        id: "foot-visual-exam",
        label: "Inspeção e neuropatia",
        title: "A imagem abre perguntas; não encerra o exame",
        release: ["Úlcera sob a cabeça do primeiro metatarso, com halo de calosidade", "Eritema ultrapassa 2 cm ao redor da lesão", "Há calor, edema e pequena quantidade de secreção purulenta", "Monofilamento de 10 g não é percebido em vários pontos de ambos os pés"],
        question: "Qual interpretação melhor integra os achados?",
        options: ["Ausência de dor excluiria gravidade", "Neuropatia sensitiva e sinais clínicos de infecção estão presentes", "A imagem confirma osteomielite", "Todo eritema em diabetes é infecção leve"],
        answer: 1,
        explanation: "Perda de sensibilidade ao monofilamento apoia neuropatia, e a combinação de calor, edema, eritema e secreção sustenta infecção clínica. A intensidade da dor pode ser enganosa na neuropatia, e a fotografia não determina sozinha profundidade ou envolvimento ósseo.",
        reflectionPrompt: "Liste os achados visuais, neurológicos e inflamatórios separadamente e explique por que ausência de dor intensa não tranquiliza neste contexto.",
        placeholder: "Visual: … | Neurológico: … | Inflamatório: … | A dor pode…",
        sourceId: "niceDiabeticFoot",
      },
      {
        id: "foot-perfusion-depth",
        label: "Perfusão e profundidade",
        title: "Examine o que a fotografia não mostra",
        release: ["Pulso pedioso direito é difícil de palpar; tibial posterior não palpável", "O pé está quente, mas o enchimento capilar é assimétrico", "A úlcera permite contato com estrutura profunda ao exame simulado", "Não há gangrena visível, porém existe preocupação com isquemia associada"],
        question: "Qual conjunto de problemas deve permanecer ativo?",
        options: ["Somente calosidade", "Infecção, neuropatia, perfusão comprometida e possível envolvimento profundo", "Apenas hiperglicemia sem relação com o pé", "Fratura traumática confirmada"],
        answer: 1,
        explanation: "A avaliação do pé diabético precisa integrar neuropatia, ulceração, infecção, deformidade e perfusão. Calor não garante circulação adequada, e suspeita de isquemia ou infecção profunda eleva o risco do membro e exige avaliação especializada urgente.",
        reflectionPrompt: "Explique quais exames à beira do leito e quais informações vasculares você registraria para diferenciar perfusão adequada de ameaça isquêmica.",
        placeholder: "Pulsos: … | Perfusão: … | Comparação: … | Avaliação vascular adicional: …",
        sourceId: "niceDiabeticFoot",
      },
      {
        id: "foot-investigation",
        label: "Exames dirigidos",
        title: "Procure extensão e não apenas um microrganismo",
        release: ["Leucócitos 17.800/mm³ e PCR 186 mg/L", "Creatinina 1,6 mg/dL, acima do valor prévio conhecido", "Radiografia mostra gás em partes moles, sem destruição óssea conclusiva", "Amostra profunda é planejada após limpeza e avaliação da equipe"],
        data: [{ label: "Leucócitos", value: "17.800/mm³", tone: "critical" }, { label: "PCR", value: "186 mg/L", tone: "critical" }, { label: "Creatinina", value: "1,6 mg/dL", tone: "attention" }, { label: "RX", value: "Inconclusivo p/ osso", tone: "attention" }],
        question: "Qual conclusão sobre osteomielite é adequada neste momento?",
        options: ["Está excluída pela radiografia inicial", "Está confirmada apenas pela PCR", "Continua possível; radiografia e marcadores normais ou inconclusivos não a excluem", "Não importa porque há uma úlcera"],
        answer: 2,
        explanation: "Infecção óssea deve ser considerada em ferida profunda ou crônica. Uma radiografia inicial pode não confirmar a alteração, e marcadores inflamatórios também não resolvem isoladamente a dúvida; investigação adicional pode ser necessária conforme avaliação especializada.",
        reflectionPrompt: "Construa uma tabela mental com evidências a favor, contra e ainda ausentes para infecção profunda ou osteomielite neste caso simulado.",
        placeholder: "A favor: … | Contra: … | Ainda falta: …",
        sourceId: "niceDiabeticFoot",
      },
      {
        id: "foot-severity-plan",
        label: "Gravidade e equipe",
        title: "A resposta precisa ser multidisciplinar",
        release: ["Persistem febre, taquicardia e alteração renal", "Há suspeita de infecção moderada a grave com possível isquemia", "O serviço dispõe de cirurgia, infectologia, vascular e equipe de pé diabético", "Culturas e avaliação da extensão estão sendo obtidas sem retardar o cuidado urgente"],
        question: "Qual princípio melhor orienta o próximo passo da simulação?",
        options: ["Aguardar melhora espontânea em casa", "Tratar apenas a glicemia e ignorar o membro", "Atendimento agudo, controle da infecção e avaliação coordenada de perfusão, tecido profundo e necessidade cirúrgica", "Escolher tratamento apenas pela aparência da foto"],
        answer: 2,
        explanation: "Sinais sistêmicos, isquemia possível e infecção profunda tornam o problema ameaçador ao membro e potencialmente à vida. O cuidado precisa ser urgente e coordenado, com decisões individualizadas segundo gravidade, perfusão, função renal, amostras e extensão tecidual.",
        reflectionPrompt: "Ordene os problemas e descreva quais equipes precisam ser acionadas, justificando o papel de cada uma no cenário apresentado.",
        placeholder: "Prioridade 1: … | Equipe… porque… | Monitorar…",
        sourceId: "niceDiabeticFoot",
      },
      {
        id: "foot-synthesis",
        label: "Síntese final",
        title: "Feche sem confundir fotografia com diagnóstico",
        release: ["O cenário sustenta pé diabético ativo infectado com sinais sistêmicos", "Neuropatia reduz a confiabilidade da dor como marcador", "Isquemia e osteomielite ainda exigem definição", "O desfecho depende de resposta clínica e avaliação multidisciplinar"],
        question: "Qual formulação final é mais precisa?",
        options: ["Úlcera superficial confirmada pela imagem", "Infecção ativa ameaçadora, com neuropatia e possíveis componentes isquêmico e ósseo ainda em avaliação", "Osteomielite definitivamente excluída", "Nenhum risco porque não existe gangrena"],
        answer: 1,
        explanation: "A síntese deve reconhecer o que está sustentado, explicitar os riscos ainda não definidos e evitar conclusões além dos dados. Ausência de gangrena ou radiografia inconclusiva não neutraliza sinais sistêmicos, perfusão anormal e possibilidade de infecção profunda.",
        reflectionPrompt: "Escreva uma síntese em três frases com problema principal, evidências de gravidade e incertezas que ainda mudariam a conduta da equipe.",
        placeholder: "Problema: … | Gravidade: … | Incertezas: …",
        sourceId: "niceDiabeticFoot",
      },
    ],
    completion: {
      title: "Pé diabético concluído: além da superfície",
      summary: "Você usou a imagem como ponto de partida e integrou neuropatia, perfusão, infecção, profundidade e repercussão sistêmica.",
      takeaways: ["Dor discreta não exclui gravidade na neuropatia", "Febre e sinais sistêmicos elevam a urgência", "Radiografia inicial não exclui osteomielite", "Cuidado do pé ativo é multidisciplinar"],
    },
  },
  {
    id: "meningococcal-sepsis",
    area: "Infectologia e emergência",
    setting: "Emergência hospitalar",
    difficulty: "Internato",
    durationMinutes: 20,
    title: "Febre, alteração mental e púrpura progressiva",
    subtitle: "Reconheça uma apresentação fulminante e aprenda a agir diante de sinais que não permitem espera passiva.",
    patient: "Mulher de 19 anos · cenário inteiramente fictício",
    focus: "Reconhecer doença meningocócica possível, priorizar estabilização e não atrasar o cuidado por busca de confirmação perfeita.",
    sensitive: true,
    sensitivityNote: "Lesões cutâneas purpúricas extensas e sinais de doença grave.",
    visual: {
      image: "/medicine/clinical/meningococcal-purpura-v1.png",
      alt: "Ilustração sintética de petequias e púrpura em pele escura",
      caption: "Imagem sintética para treino de reconhecimento. Erupções podem variar e ser difíceis de identificar em diferentes tons de pele.",
    },
    triage: [{ label: "Temperatura", value: "39,4 °C", tone: "critical" }, { label: "PA", value: "84/48 mmHg", tone: "critical" }, { label: "FC", value: "138 bpm", tone: "critical" }, { label: "Glasgow", value: "12", tone: "critical" }],
    steps: [
      {
        id: "meningo-recognition",
        label: "Reconhecimento",
        title: "O conjunto importa mais que um sintoma isolado",
        release: ["Febre alta e cefaleia iniciadas na manhã de hoje", "Vômitos, mialgia intensa e piora rápida nas últimas duas horas", "Está sonolenta e responde de forma confusa", "Familiares notaram manchas arroxeadas surgindo nas pernas"],
        question: "Qual hipótese operacional precisa ser priorizada sem esperar a apresentação clássica completa?",
        options: ["Doença meningocócica invasiva possível com sepse", "Dermatite de contato estável", "Enxaqueca sem repercussão sistêmica", "Anemia microcítica isolada"],
        answer: 0,
        explanation: "Febre, deterioração rápida, alteração de consciência, instabilidade e lesões hemorrágicas não branqueáveis formam um conjunto de alto risco para doença meningocócica invasiva. Nem todas as pessoas apresentam todos os sinais clássicos, e a ausência de rigidez nucal não tranquiliza.",
        reflectionPrompt: "Resuma em uma frase quais dados tornam este caso tempo-dependente e quais ameaças fisiológicas precisam ser avaliadas imediatamente.",
        placeholder: "É tempo-dependente porque… | Ameaças imediatas: …",
        sourceId: "niceMeningococcal",
        hint: "Pense em uma síndrome infecciosa sistêmica com choque e lesão vascular cutânea.",
      },
      {
        id: "meningo-rash",
        label: "Exame da pele",
        title: "Petequias e púrpura são sinais, não decoração",
        release: ["Lesões puntiformes não desaparecem à pressão", "Há placas purpúricas irregulares maiores que 2 mm", "Novas lesões surgiram durante a avaliação", "Na pele escura, a inspeção incluiu conjuntivas, palmas e plantas"],
        question: "Qual característica representa um sinal de alerta específico neste contexto?",
        options: ["Erupção pruriginosa que desaparece à pressão", "Púrpura hemorrágica não branqueável e progressiva", "Uma única mácula antiga e estável", "Ausência de lesão no rosto"],
        answer: 1,
        explanation: "Púrpura não branqueável, especialmente quando progride ou se associa a sinais de meningite, é um alerta forte para doença meningocócica. A avaliação deve percorrer toda a pele e reconhecer que algumas alterações são mais difíceis de visualizar em tons escuros.",
        reflectionPrompt: "Descreva como você examinaria e documentaria a distribuição, progressão, tamanho e resposta à pressão das lesões sem depender apenas da fotografia.",
        placeholder: "Distribuição: … | Progressão: … | Branqueamento: … | Outros locais: …",
        sourceId: "niceMeningococcal",
      },
      {
        id: "meningo-stabilization",
        label: "Estabilização",
        title: "Trate a deterioração como uma emergência",
        release: ["PA permanece 84/48 mmHg e extremidades estão frias", "Tempo de enchimento capilar é de 5 segundos", "SpO₂ 93% em ar ambiente e FR 30 irpm", "A equipe de emergência e o protocolo institucional de sepse foram acionados"],
        data: [{ label: "PA", value: "84/48", tone: "critical" }, { label: "FC", value: "138", tone: "critical" }, { label: "TEC", value: "5 s", tone: "critical" }, { label: "SpO₂", value: "93%", tone: "attention" }],
        question: "Qual postura é mais segura enquanto a investigação é organizada?",
        options: ["Observar por algumas horas antes de agir", "Priorizar suporte fisiológico e tratamento institucional urgente, em paralelo à investigação", "Esperar a erupção atingir o rosto", "Liberar porque a idade é baixa"],
        answer: 1,
        explanation: "Choque, alteração neurológica e possível doença meningocócica exigem resposta emergencial. Estabilização e tratamento tempo-dependente precisam caminhar em paralelo aos exames; a busca por confirmação não deve criar atraso perigoso diante de uma apresentação altamente suspeita.",
        reflectionPrompt: "Organize as prioridades fisiológicas desta etapa e explique quais tarefas podem ocorrer simultaneamente para evitar atraso de cuidado.",
        placeholder: "Via aérea/respiração: … | Circulação: … | Em paralelo: …",
        sourceId: "niceMeningococcal",
      },
      {
        id: "meningo-investigation",
        label: "Exames e gravidade",
        title: "Colete dados sem perder o relógio",
        release: ["Lactato 5,6 mmol/L e plaquetas 68.000/mm³", "Creatinina 1,9 mg/dL e INR 1,8", "Leucócitos 3.200/mm³ com neutrofilia relativa", "Culturas foram coletadas sem atrasar o protocolo de emergência"],
        data: [{ label: "Lactato", value: "5,6 mmol/L", tone: "critical" }, { label: "Plaquetas", value: "68 mil", tone: "critical" }, { label: "Creatinina", value: "1,9 mg/dL", tone: "critical" }, { label: "INR", value: "1,8", tone: "critical" }],
        question: "O que esses dados acrescentam ao caso?",
        options: ["Mostram disfunção orgânica e coagulopatia compatíveis com doença sistêmica grave", "Excluem infecção por leucócitos baixos", "Confirmam dermatite alérgica", "Eliminam a necessidade de monitorização"],
        answer: 0,
        explanation: "Hipoperfusão, trombocitopenia, alteração de coagulação e disfunção renal reforçam a gravidade sistêmica. Leucopenia não exclui infecção invasiva e pode acompanhar doença grave; nenhum exame isolado substitui o reconhecimento clínico e a resposta urgente.",
        reflectionPrompt: "Explique como lactato, plaquetas, coagulação, rim e contagem de leucócitos modificam sua avaliação de gravidade e de risco imediato.",
        placeholder: "Perfusão: … | Coagulação: … | Órgãos: … | Leucócitos: …",
        sourceId: "cdcMeningococcal",
      },
      {
        id: "meningo-evolution",
        label: "Evolução e complicações",
        title: "Sobreviver ao choque não encerra o caso",
        release: ["Após cuidado intensivo, há melhora hemodinâmica progressiva", "Algumas lesões cutâneas evoluem e exigem avaliação especializada", "Triagem auditiva e neurológica será organizada no seguimento", "Família recebe comunicação estruturada e apoio psicossocial"],
        question: "Qual plano de continuidade é mais completo?",
        options: ["Alta sem seguimento após normalizar a pressão", "Acompanhar possíveis sequelas neurológicas, auditivas, cutâneas, renais e psicossociais", "Avaliar apenas a febre", "Ignorar a pele porque não define o agente"],
        answer: 1,
        explanation: "Doença meningocócica e meningite bacteriana podem deixar repercussões em múltiplos domínios. O seguimento deve considerar audição, cognição, neurologia, pele, rim, aspectos ortopédicos e impacto psicossocial, adaptado ao curso clínico de cada pessoa.",
        reflectionPrompt: "Monte um plano de seguimento por domínios e justifique por que uma recuperação hemodinâmica inicial não encerra a vigilância clínica.",
        placeholder: "Neurológico: … | Audição: … | Pele/membro: … | Psicossocial: …",
        sourceId: "niceMeningococcal",
      },
      {
        id: "meningo-synthesis",
        label: "Síntese final",
        title: "Nomeie a síndrome e preserve a incerteza",
        release: ["Apresentação foi hiperaguda, com febre, choque e alteração mental", "Erupção não branqueável progrediu durante a avaliação", "Laboratório mostrou hipoperfusão, coagulopatia e disfunção orgânica", "Confirmação etiológica não era necessária para reconhecer a emergência"],
        question: "Qual síntese final é mais precisa?",
        options: ["Erupção benigna confirmada pela imagem", "Síndrome compatível com doença meningocócica invasiva e sepse grave, tratada como emergência enquanto a etiologia é confirmada", "Meningite excluída por ausência de um sinal", "Choque resolvido, portanto caso sem risco de sequela"],
        answer: 1,
        explanation: "A formulação segura reconhece a síndrome sustentada por tempo de evolução, instabilidade, pele e disfunção orgânica, sem fingir confirmação microbiológica. O valor do exercício está em agir diante do risco e manter acompanhamento das complicações possíveis.",
        reflectionPrompt: "Escreva uma síntese com síndrome, evidências de gravidade, conduta temporal e incerteza etiológica que ainda precisa de confirmação.",
        placeholder: "Síndrome: … | Evidências: … | Urgência: … | Ainda confirmar: …",
        sourceId: "cdcMeningococcal",
      },
    ],
    completion: {
      title: "Emergência concluída: reconheça antes da perfeição",
      summary: "Você reconheceu choque e púrpura progressiva como sinais de alto risco, organizou resposta paralela à investigação e incluiu sequelas no desfecho.",
      takeaways: ["A erupção pode surgir ou mudar rapidamente", "Ausência de um sinal clássico não exclui doença", "Choque e disfunção orgânica exigem ação paralela", "Seguimento vai além da sobrevida imediata"],
    },
  },
];
