export type SemiologyPhase = "Fundamentos" | "Coleta clínica" | "Integração" | "Prática segura";

export interface SemiologyModule {
  id: string;
  number: number;
  phase: SemiologyPhase;
  title: string;
  subtitle: string;
  duration: string;
  goals: string[];
  concepts: Array<{ title: string; text: string }>;
  pearl: string;
  warning: string;
  question: {
    prompt: string;
    options: string[];
    answer: number;
    explanation: string;
  };
  sourceIds: string[];
}

export const semiologyModules: SemiologyModule[] = [
  {
    id: "foundations",
    number: 1,
    phase: "Fundamentos",
    title: "Semiologia básica",
    subtitle: "O vocabulário do encontro clínico",
    duration: "20 min",
    goals: ["Distinguir sintoma, sinal e síndrome", "Separar dado subjetivo de dado objetivo", "Descrever sem concluir cedo demais"],
    concepts: [
      { title: "Sintoma", text: "Experiência percebida e relatada pela pessoa, como dor, náusea ou falta de ar." },
      { title: "Sinal", text: "Achado observado ou medido durante a avaliação, como temperatura, edema ou alteração da marcha." },
      { title: "Síndrome", text: "Conjunto reconhecível de sinais e sintomas que pode ter mais de uma causa." },
      { title: "Problema clínico", text: "Representação organizada de um achado relevante, ainda sem obrigar um diagnóstico definitivo." },
    ],
    pearl: "Registre primeiro o que foi relatado e observado; interprete depois.",
    warning: "Um achado isolado raramente fecha um diagnóstico.",
    question: {
      prompt: "A pessoa relata ardor ao urinar e o exame mostra temperatura de 38,2 °C. Qual classificação está correta?",
      options: ["Ardor e temperatura são sintomas", "Ardor é sintoma; temperatura medida é sinal", "Ardor é sinal; temperatura é sintoma", "Ambos já são diagnósticos"],
      answer: 1,
      explanation: "O ardor é uma experiência relatada; a temperatura aferida é um dado objetivo. Nenhum dos dois, isoladamente, estabelece a causa.",
    },
    sourceIds: ["ncbiClinicalMethods"],
  },
  {
    id: "complete-history",
    number: 2,
    phase: "Coleta clínica",
    title: "Anamnese completa",
    subtitle: "Da abertura à revisão de sistemas",
    duration: "35 min",
    goals: ["Organizar os componentes da história", "Começar com perguntas abertas", "Caracterizar a queixa sem perder contexto e segurança"],
    concepts: [
      { title: "Identificação e fonte", text: "Quem é a pessoa, como prefere ser chamada e quem fornece a história." },
      { title: "Queixa e história atual", text: "Motivo principal nas palavras da pessoa, início, evolução, características, fatores associados e impacto." },
      { title: "Antecedentes", text: "Condições prévias, internações, cirurgias, saúde familiar, contexto reprodutivo quando pertinente e imunização." },
      { title: "Medicamentos e alergias", text: "Nome, uso, adesão e reação alérgica descrita — não apenas a palavra ‘alergia’." },
      { title: "Hábitos e contexto", text: "Trabalho, moradia, alimentação, sono, atividade, substâncias, apoio, funcionalidade e segurança." },
      { title: "Revisão de sistemas", text: "Rastreamento orientado por sistemas para encontrar dados não mencionados espontaneamente." },
    ],
    pearl: "Comece amplo, depois focalize e termine verificando se algo importante ficou de fora.",
    warning: "O roteiro organiza a conversa; não deve transformá-la em interrogatório.",
    question: {
      prompt: "Qual abertura tende a produzir uma história inicial menos dirigida?",
      options: ["A dor é em aperto, certo?", "Conte o que trouxe você hoje e como isso começou", "Você não tomou o remédio, não é?", "Responda apenas sim ou não"],
      answer: 1,
      explanation: "Uma pergunta aberta convida a narrativa. Perguntas focadas entram depois para esclarecer pontos específicos.",
    },
    sourceIds: ["ncbiMedicalInterview", "openstaxInterview"],
  },
  {
    id: "general-survey",
    number: 3,
    phase: "Coleta clínica",
    title: "Exame físico geral",
    subtitle: "Observar antes de tocar",
    duration: "25 min",
    goals: ["Realizar uma inspeção geral organizada", "Descrever consciência, conforto, postura e mobilidade", "Reconhecer que a avaliação começa no primeiro contato"],
    concepts: [
      { title: "Impressão geral", text: "Estado aparente, conforto ou sofrimento, interação, fala e participação no encontro." },
      { title: "Consciência e orientação", text: "Nível de alerta e capacidade de se situar, respeitando limitações de linguagem, audição e cognição." },
      { title: "Pele e hidratação", text: "Coloração, umidade, integridade e achados visíveis descritos sem inferência precipitada." },
      { title: "Postura, marcha e funcionalidade", text: "Como a pessoa se posiciona, levanta, caminha e realiza movimentos necessários." },
      { title: "Comunicação não verbal", text: "Expressão facial, contato visual, proteção de uma região e esforço respiratório podem orientar perguntas." },
    ],
    pearl: "A inspeção geral acontece durante toda a consulta, não apenas em um minuto separado.",
    warning: "Aparência não substitui medidas nem autoriza julgamentos sobre comportamento ou adesão.",
    question: {
      prompt: "Qual registro é mais descritivo e menos interpretativo?",
      options: ["Paciente exagerando a dor", "Pessoa inquieta, com expressão contraída e protegendo o abdome", "Pessoa com apendicite", "Paciente pouco colaborativo"],
      answer: 1,
      explanation: "O registro descreve o que foi observado sem atribuir intenção ou fechar uma causa.",
    },
    sourceIds: ["openstaxAssessment"],
  },
  {
    id: "vital-signs",
    number: 4,
    phase: "Coleta clínica",
    title: "Sinais vitais",
    subtitle: "Medir, validar, comparar e registrar",
    duration: "40 min",
    goals: ["Reconhecer as medidas essenciais", "Identificar fatores que alteram a aferição", "Interpretar tendência e contexto antes de rotular"],
    concepts: [
      { title: "Pressão arterial", text: "Exige equipamento e manguito adequados, posicionamento, repouso e técnica padronizada." },
      { title: "Frequência cardíaca", text: "Registre frequência, ritmo e qualidade quando avaliável; confirme achados inesperados." },
      { title: "Frequência respiratória", text: "Observe frequência, padrão e esforço sem alterar involuntariamente a respiração da pessoa." },
      { title: "Temperatura", text: "A via de aferição, o dispositivo e o contexto influenciam a interpretação." },
      { title: "Saturação periférica", text: "Analise sinal do aparelho, perfusão, movimento, esmalte e coerência com a avaliação clínica." },
      { title: "Dor", text: "É autorrelatada e multidimensional; intensidade é apenas uma parte da avaliação." },
    ],
    pearl: "Uma tendência coerente costuma informar mais que um valor isolado.",
    warning: "Valor inesperado deve ser tecnicamente validado e interpretado no contexto da pessoa — nunca ignorado nem tratado automaticamente pelo site.",
    question: {
      prompt: "Uma saturação inesperadamente baixa aparece em uma pessoa sem sinais de desconforto e com mãos frias. Qual é o primeiro raciocínio técnico?",
      options: ["Registrar sem conferir", "Concluir insuficiência respiratória", "Verificar qualidade do sinal, perfusão, sensor e repetir conforme protocolo", "Desligar o aparelho"],
      answer: 2,
      explanation: "É preciso validar a medida e compará-la com o quadro observado. Isso não substitui avaliação profissional quando houver alteração real ou preocupação clínica.",
    },
    sourceIds: ["openstaxVitalSigns", "openstaxAssessment"],
  },
  {
    id: "exam-techniques",
    number: 5,
    phase: "Coleta clínica",
    title: "Técnicas do exame físico",
    subtitle: "Inspeção, palpação, percussão e ausculta",
    duration: "30 min",
    goals: ["Conhecer a finalidade de cada técnica", "Aplicar uma sequência coerente", "Lembrar a exceção clássica do exame abdominal"],
    concepts: [
      { title: "Inspeção", text: "Observação sistemática de forma, simetria, movimento, coloração e comportamento." },
      { title: "Palpação", text: "Uso do tato para avaliar temperatura, textura, sensibilidade, pulsos, mobilidade ou massas, respeitando conforto e consentimento." },
      { title: "Percussão", text: "Produção e interpretação de sons e vibrações para estimar características de estruturas subjacentes." },
      { title: "Ausculta", text: "Escuta sistemática com técnica e ambiente adequados; deve ser correlacionada com os demais achados." },
      { title: "Abdome", text: "Ausculta costuma anteceder percussão e palpação para reduzir interferência nos ruídos intestinais." },
    ],
    pearl: "Explique o que fará, obtenha consentimento e preserve exposição mínima necessária.",
    warning: "Técnicas manuais precisam de demonstração e supervisão presencial para serem aprendidas com segurança.",
    question: {
      prompt: "Qual sequência é tradicionalmente usada no exame abdominal?",
      options: ["Inspeção → ausculta → percussão → palpação", "Palpação → inspeção → ausculta → percussão", "Ausculta → palpação → inspeção → percussão", "Percussão → palpação → inspeção → ausculta"],
      answer: 0,
      explanation: "No abdome, a ausculta costuma ser realizada antes de percussão e palpação. Outros sistemas frequentemente seguem inspeção, palpação, percussão e ausculta.",
    },
    sourceIds: ["openstaxPhysicalAssessment", "ncbiChestExam"],
  },
  {
    id: "systems-exam",
    number: 6,
    phase: "Coleta clínica",
    title: "Exame por sistemas",
    subtitle: "Do rastreio geral ao exame focal",
    duration: "45 min",
    goals: ["Relacionar história e foco do exame", "Organizar sistemas sem esquecer comparação bilateral", "Reconhecer limites do treinamento virtual"],
    concepts: [
      { title: "Cardiovascular", text: "Perfusão, pulsos, pressão, inspeção e palpação precordial, ausculta e sinais periféricos conforme objetivo e supervisão." },
      { title: "Respiratório", text: "Padrão e esforço, expansibilidade, percussão e ausculta correlacionados à história." },
      { title: "Abdominal", text: "Inspeção, ausculta, percussão e palpação progressiva, deixando área dolorosa por último." },
      { title: "Neurológico", text: "Estado mental, pares cranianos, força, sensibilidade, coordenação, reflexos e marcha conforme indicação." },
      { title: "Cabeça e pescoço", text: "Olhos, ouvidos, nariz, boca, orofaringe, linfonodos e tireoide conforme contexto." },
      { title: "Musculoesquelético", text: "Inspeção, amplitude de movimento, força, estabilidade e comparação entre lados sem causar dor." },
    ],
    pearl: "A história define a profundidade do exame; o exame testa perguntas levantadas pela história.",
    warning: "Não pratique manobras dolorosas, íntimas ou potencialmente perigosas sem treinamento e supervisão apropriados.",
    question: {
      prompt: "Em uma queixa respiratória, qual conjunto forma uma avaliação inicial mais coerente?",
      options: ["Apenas auscultar", "Observar padrão e esforço, validar sinais vitais e realizar exame respiratório sistemático", "Solicitar exames antes de conversar", "Avaliar somente a garganta"],
      answer: 1,
      explanation: "A avaliação combina contexto, observação, medidas e técnicas focadas; nenhuma etapa isolada substitui as demais.",
    },
    sourceIds: ["openstaxPhysicalAssessment", "ncbiChestExam"],
  },
  {
    id: "terminology",
    number: 7,
    phase: "Integração",
    title: "Terminologia médica",
    subtitle: "Traduzir termos sem perder a pessoa",
    duration: "25 min",
    goals: ["Reconhecer termos frequentes", "Usar descrições precisas", "Explicar em linguagem acessível ao paciente"],
    concepts: [
      { title: "Respiração e deglutição", text: "Dispneia é sensação de dificuldade respiratória; disfagia é dificuldade para engolir." },
      { title: "Urina e sangramento", text: "Disúria é dor ou ardor ao urinar; hematêmese é vômito com sangue; melena descreve fezes negras compatíveis com sangue digerido." },
      { title: "Cor e volume", text: "Cianose, icterícia e edema descrevem achados diferentes e exigem contexto." },
      { title: "Tempo", text: "Agudo, subagudo, crônico, episódico, progressivo e recorrente organizam evolução — não gravidade por si só." },
    ],
    pearl: "No prontuário, seja preciso; com a pessoa, traduza e confirme entendimento.",
    warning: "Não use um termo técnico como substituto de uma descrição incompleta.",
    question: {
      prompt: "Qual termo corresponde à dificuldade para engolir?",
      options: ["Dispneia", "Disfagia", "Disúria", "Disartria"],
      answer: 1,
      explanation: "Disfagia é dificuldade de deglutição. O glossário da página permite comparar termos semelhantes.",
    },
    sourceIds: ["ncbiClinicalMethods"],
  },
  {
    id: "clinical-reasoning",
    number: 8,
    phase: "Integração",
    title: "Raciocínio clínico inicial",
    subtitle: "Dos dados à representação do problema",
    duration: "35 min",
    goals: ["Agrupar achados relevantes", "Construir uma síntese em uma frase", "Gerar hipóteses sem fechamento prematuro"],
    concepts: [
      { title: "Coletar", text: "História, observação, exame e dados disponíveis, sempre avaliando qualidade e fonte." },
      { title: "Representar", text: "Resumir quem é a pessoa, qual síndrome ou problema predomina, tempo de evolução e achados discriminadores." },
      { title: "Priorizar", text: "Separar o provável do perigoso e do tratável, considerando urgência e contexto." },
      { title: "Testar", text: "Buscar achados que aumentem ou reduzam a plausibilidade de cada hipótese e reconhecer incerteza." },
      { title: "Reavaliar", text: "Atualizar a síntese quando novas informações aparecem, evitando ancoragem." },
    ],
    pearl: "Uma boa síntese comprime dados sem inventar certeza.",
    warning: "Listas enormes de diagnósticos não substituem priorização nem supervisão clínica.",
    question: {
      prompt: "Qual síntese é mais útil para começar o raciocínio?",
      options: ["Paciente com tudo alterado", "Mulher de 68 anos, previamente independente, com início súbito de fraqueza direita e alteração da fala", "Provavelmente AVC, sem precisar de mais dados", "Idosa doente"],
      answer: 1,
      explanation: "A frase reúne contexto, linha de base, tempo e achados discriminadores sem transformar hipótese em certeza.",
    },
    sourceIds: ["ncbiDataAnalysis", "namDiagnosticProcess"],
  },
  {
    id: "clinical-record",
    number: 9,
    phase: "Integração",
    title: "Prontuário e evolução",
    subtitle: "Registrar para comunicar e dar continuidade",
    duration: "35 min",
    goals: ["Separar dados subjetivos e objetivos", "Conhecer a estrutura SOAP", "Escrever com clareza, pertinência e rastreabilidade"],
    concepts: [
      { title: "S — Subjetivo", text: "Relato da pessoa, evolução, sintomas, contexto e informações fornecidas por terceiros identificados." },
      { title: "O — Objetivo", text: "Observações, sinais vitais, exame físico e resultados disponíveis, com técnica ou fonte quando relevante." },
      { title: "A — Avaliação", text: "Representação dos problemas, hipóteses priorizadas e incertezas — adequada ao nível de formação e supervisão." },
      { title: "P — Plano", text: "Próximos passos educacionais ou assistenciais definidos pela equipe responsável; no simulador, apenas plano de aprendizagem." },
    ],
    pearl: "O prontuário deve permitir que outra pessoa compreenda o que aconteceu, o que foi pensado e o que ficou combinado.",
    warning: "Nunca insira dados reais de pacientes neste exercício. Use somente casos fictícios.",
    question: {
      prompt: "Em qual parte do SOAP entra ‘refere dor iniciada há duas horas’?",
      options: ["Subjetivo", "Objetivo", "Avaliação", "Plano"],
      answer: 0,
      explanation: "É um dado relatado pela pessoa. Uma medida aferida ou achado observado entraria em Objetivo.",
    },
    sourceIds: ["cfmMedicalRecord", "ncbiDataAnalysis"],
  },
  {
    id: "communication",
    number: 10,
    phase: "Prática segura",
    title: "Comunicação médico-paciente",
    subtitle: "Vínculo, clareza e decisão compartilhada",
    duration: "30 min",
    goals: ["Apresentar-se e definir a agenda", "Alternar perguntas abertas e fechadas", "Usar escuta, empatia e verificação de entendimento"],
    concepts: [
      { title: "Abertura", text: "Apresente-se, confirme identidade e preferência de tratamento, garanta privacidade e explique o objetivo." },
      { title: "Escuta", text: "Evite interrupção precoce, reconheça emoções e use as palavras da pessoa para esclarecer." },
      { title: "Perguntas", text: "Abertas exploram; fechadas confirmam detalhes. Perguntas neutras reduzem julgamento e sugestão." },
      { title: "Fechamento", text: "Resuma, confira correções, explique próximos passos e peça que a pessoa demonstre o que compreendeu." },
    ],
    pearl: "Empatia pode ser concreta: nomeie a emoção, valide a experiência e ofereça parceria.",
    warning: "Privacidade, acessibilidade, idioma, cultura e autonomia fazem parte da qualidade da conversa.",
    question: {
      prompt: "A pessoa fica em silêncio após receber uma informação difícil. Qual resposta preserva melhor o vínculo?",
      options: ["Mudar imediatamente de assunto", "Preencher o silêncio com muitos detalhes", "Dar espaço e dizer que percebe que a informação foi difícil", "Dizer que precisa ser forte"],
      answer: 2,
      explanation: "Reconhecer a emoção e tolerar o silêncio abre espaço para a pessoa responder e formular dúvidas.",
    },
    sourceIds: ["ncbiMedicalInterview", "openstaxInterview"],
  },
  {
    id: "ethics-safety",
    number: 11,
    phase: "Prática segura",
    title: "Ética e biossegurança",
    subtitle: "Antes de qualquer técnica",
    duration: "30 min",
    goals: ["Reconhecer consentimento e sigilo", "Aplicar identificação e higiene das mãos", "Entender limites de competência e supervisão"],
    concepts: [
      { title: "Consentimento", text: "Explique finalidade, etapas, desconfortos previsíveis e possibilidade de interromper; confirme concordância antes do exame." },
      { title: "Sigilo", text: "Informações de saúde são sensíveis; acesso e compartilhamento devem seguir necessidade, autorização e normas aplicáveis." },
      { title: "Identificação", text: "Confirme a pessoa com identificadores apropriados antes de cuidado ou procedimento, conforme protocolo institucional." },
      { title: "Higiene das mãos", text: "Realize nos momentos indicados; luvas não substituem higiene das mãos." },
      { title: "EPIs e ambiente", text: "Selecione conforme risco de exposição e regras locais; descarte e limpeza também integram a segurança." },
      { title: "Limites", text: "Estudantes devem se identificar como estudantes, atuar com consentimento e supervisão e não exceder competência." },
    ],
    pearl: "Segurança e respeito não são uma etapa final; moldam todo o encontro.",
    warning: "Este módulo ensina princípios. Protocolos da instituição e orientação de supervisores prevalecem na prática.",
    question: {
      prompt: "Qual afirmação sobre luvas é correta?",
      options: ["Substituem higiene das mãos", "Eliminam a necessidade de avaliar risco", "São usadas conforme risco, mas não substituem higiene das mãos", "Devem ser usadas em toda conversa"],
      answer: 2,
      explanation: "Luvas têm indicações específicas e não substituem a higiene das mãos nos momentos recomendados.",
    },
    sourceIds: ["anvisaHandHygiene", "cfmEthics"],
  },
  {
    id: "integrated-case",
    number: 12,
    phase: "Prática segura",
    title: "Caso clínico básico",
    subtitle: "Conversa → exame → problemas → registro",
    duration: "45 min",
    goals: ["Integrar anamnese e exame geral", "Priorizar dados e reconhecer alerta", "Produzir uma síntese e um registro estruturado"],
    concepts: [
      { title: "1. Preparar", text: "Ambiente, identificação, apresentação, higiene das mãos, privacidade e consentimento." },
      { title: "2. Ouvir", text: "Narrativa inicial, caracterização da queixa, antecedentes, medicamentos, alergias e contexto." },
      { title: "3. Observar e medir", text: "Exame geral, sinais vitais tecnicamente válidos e exame focal coerente com a história." },
      { title: "4. Integrar", text: "Lista de problemas, síntese, hipóteses iniciais, sinais de alerta e lacunas." },
      { title: "5. Comunicar", text: "Registro SOAP fictício, discussão com supervisor e explicação clara à pessoa." },
    ],
    pearl: "O objetivo inicial não é adivinhar o diagnóstico: é colher dados confiáveis e reconhecer prioridades com segurança.",
    warning: "Casos do site são fictícios e não devem ser usados para decidir atendimento de pessoas reais.",
    question: {
      prompt: "Após concluir este módulo, qual é o próximo treino mais adequado no site?",
      options: ["Diagnosticar pessoas reais", "Laboratório de Anamnese com pacientes virtuais", "Pular diretamente para cirurgia", "Prescrever medicamentos"],
      answer: 1,
      explanation: "A trilha prepara para os pacientes virtuais, onde perguntas, síntese e decisões educacionais recebem feedback.",
    },
    sourceIds: ["ncbiClinicalMethods", "openstaxAssessment", "anvisaHandHygiene"],
  },
];

export const semiologyTechniques = [
  { id: "inspection", name: "Inspeção", description: "Observe de forma intencional antes de tocar.", color: "#5b8f83" },
  { id: "palpation", name: "Palpação", description: "Use o tato com consentimento, técnica e progressão.", color: "#b07b59" },
  { id: "percussion", name: "Percussão", description: "Produza sons para inferir características subjacentes.", color: "#8c79a8" },
  { id: "auscultation", name: "Ausculta", description: "Escute sistematicamente e correlacione com os demais achados.", color: "#457b9d" },
] as const;

export const semiologyTerms = [
  ["Dispneia", "Sensação de dificuldade ou desconforto para respirar"],
  ["Ortopneia", "Desconforto respiratório ao deitar, aliviado ao elevar o tronco"],
  ["Disfagia", "Dificuldade para engolir"],
  ["Odinofagia", "Dor ao engolir"],
  ["Disúria", "Dor ou ardor ao urinar"],
  ["Poliúria", "Aumento do volume urinário"],
  ["Hematêmese", "Vômito com sangue"],
  ["Hemoptise", "Eliminação de sangue pela tosse, originado das vias respiratórias"],
  ["Melena", "Fezes negras compatíveis com sangue digerido"],
  ["Hematúria", "Presença de sangue na urina"],
  ["Edema", "Acúmulo de líquido no espaço intersticial"],
  ["Cianose", "Coloração azulada ou arroxeada de pele ou mucosas"],
  ["Icterícia", "Coloração amarelada de pele, mucosas ou escleras"],
  ["Síncope", "Perda transitória de consciência e tônus postural com recuperação espontânea"],
  ["Parestesia", "Sensação anormal, como formigamento ou dormência"],
  ["Astenia", "Sensação de fraqueza ou falta de energia"],
  ["Anorexia", "Perda ou redução do apetite no sentido clínico"],
  ["Prurido", "Coceira"],
  ["Oligúria", "Redução do volume urinário"],
  ["Disartria", "Alteração motora da articulação da fala"],
] as const;

export const semiologyVitalChecks = [
  { id: "bp", label: "Pressão arterial", equipment: "Manguito adequado e aparelho validado", verify: "Repouso, posição, braço apoiado, tamanho do manguito e repetição quando indicada" },
  { id: "pulse", label: "Pulso", equipment: "Relógio ou monitor conforme contexto", verify: "Frequência, ritmo, qualidade e coerência com a pessoa" },
  { id: "respiration", label: "Respiração", equipment: "Observação e relógio", verify: "Frequência, ritmo, profundidade, esforço e capacidade de falar" },
  { id: "temperature", label: "Temperatura", equipment: "Termômetro e via apropriada", verify: "Via, dispositivo, condições locais e registro da técnica" },
  { id: "spo2", label: "Saturação", equipment: "Oxímetro adequado", verify: "Sinal, perfusão, movimento, posicionamento e tendência" },
  { id: "pain", label: "Dor", equipment: "Escala apropriada e conversa", verify: "Local, caráter, intensidade, tempo, impacto e significado para a pessoa" },
] as const;

export const semiologySourceIds = Array.from(new Set(semiologyModules.flatMap((module) => module.sourceIds)));
