import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        heading: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        subject: {
          math: "hsl(var(--subject-math))",
          bio: "hsl(var(--subject-bio))",
          chem: "hsl(var(--subject-chem))",
          physics: "hsl(var(--subject-physics))",
          portuguese: "hsl(var(--subject-portuguese))",
          history: "hsl(var(--subject-history))",
          geography: "hsl(var(--subject-geography))",
          english: "hsl(var(--subject-english))",
          redacao: "hsl(var(--subject-redacao))",
          simulado: "hsl(var(--subject-simulado))",
          "direito-const": "hsl(var(--subject-direito-const))",
          "direito-adm": "hsl(var(--subject-direito-adm))",
          "direito-penal": "hsl(var(--subject-direito-penal))",
          "direito-civil": "hsl(var(--subject-direito-civil))",
          rlm: "hsl(var(--subject-rlm))",
          info: "hsl(var(--subject-info))",
          atualidades: "hsl(var(--subject-atualidades))",
          "adm-publica": "hsl(var(--subject-adm-publica))",
          contabilidade: "hsl(var(--subject-contabilidade))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-in": { from: { opacity: "0", transform: "translateX(-12px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "page-slide-in": { "0%": { opacity: "0", transform: "translateX(40px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "page-slide-back": { "0%": { opacity: "0", transform: "translateX(-40px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "swap-pop": {
          "0%": { transform: "scale(0.85)", filter: "brightness(1.6)" },
          "55%": { transform: "scale(1.08)", filter: "brightness(1.25)" },
          "100%": { transform: "scale(1)", filter: "brightness(1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "page-slide-in": "page-slide-in 0.3s cubic-bezier(0.16,1,0.3,1)",
        "page-slide-back": "page-slide-back 0.3s cubic-bezier(0.16,1,0.3,1)",
        "swap-pop": "swap-pop 0.45s cubic-bezier(0.22,1,0.36,1)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
